config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'articles#index'
  get 'articles/index'

  # get 'articles', to: 'articles#index'
  # get 'articles/new', to: 'articles#new', as: 'new_article'
  # post 'articles', to: 'articles#create'
  # get 'articles/:id', to: 'articles#show', as: 'article'
  # get 'articles/:id/edit', to: 'articles#edit', as: 'edit_article'
  # patch 'articles/:id', to: 'articles#update'
  # delete 'articles/:id', to: 'articles#destroy' - resources generuje to wszystko

  resources :articles do
    get 'toggle_visibility', on: :member
    get 'most_commented', on: :member
    resources :comments do
      resources :scores, only: %i[create destroy]
    end
    resources :likes, only: %i[create destroy]
  end

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  include ActiveModel::Validations

  validates :body, presence: true, length: 6..500
  belongs_to :article, counter_cache: true
  belongs_to :user

  has_many :scores
  has_many :users, through: :scores


  def score_value
    score_value = 0
    scores.each do |score|
      score_value += score.value
    end
    return score_value
  end



end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_article
  before_action :find_comment, only: [:destroy, :update, :edit]
  before_action :logged_in?, only: [:create]
  before_action :authenticate_user, only: [:destroy, :edit, :update]

  def create
    @comment = Comment.new(comment_params)
    @comment.article = @article
    @like = Like.find_or_initialize_by(article: @article, user: current_user)
    @comment.user = current_user
    if @comment.save
      # session[:commenter] = @comment.user
      flash[:notice] = "You have successfuly added a comment."
      redirect_to article_path(@article)
    else
      render 'articles/show'
    end
  end

  def edit
  end

  def update
    if @comment.update(comment_params)
      flash[:notice] = "You have successfuly updated the comment."
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def destroy
    @comment.destroy
    flash[:notice] = "You have deleted the comment."
    redirect_to article_path(@article)
  end

  private

  def authenticate_user
    if @comment.user != current_user && !current_user&.admin?
      flash[:alert] = "You are not allowed to do this."
      redirect_to article_path(@article)
      return false
    end
  true
  end

  def logged_in?
    current_user
  end

  def find_comment
    @comment = Comment.find(params[:id])
  end

  def find_article
    @article = Article.published.find(params[:article_id])
  end


  def comment_params
    comment_params = params.require(:comment).permit(:body)
  end

end

app/views/comments/_comment.html.erb
<div class="comment" id="comment-<%=comment.id%>" style="display:block;">
  <p>
    <strong>Commenter:</strong>
    <%= comment.user.email %>
  </p>
  <p>
    <strong>Body:</strong>
    <%= simple_format(comment.body) %>
  </p>
  <p>
    <strong>Date created:</strong>
    <%= comment.created_at %>

  <p id="score-comment-<%=comment.id%>"><%= comment.score_value %></p>
  <p>
    <% if comment&.scores.any? { |score| score.user == current_user } %>
        <%= link_to 'delete your rating', article_comment_score_path(@article, comment, comment.scores.for_user(current_user)), method: :delete %>
    <% else %>
      <%= form_for [comment, @score], url: article_comment_scores_path(@article, comment) do |f| %>
        <p>
          <%= f.label :value, "score comment:" %>
          <%= f.collection_radio_buttons :value, [[1, '+'] ,[-1, '-']], :first, :last %>
        </p>
        <p>
          <%= f.submit %>
        </p>
      <% end %>
    </p>
  <% end %>
  </p>

  <% if comment.user == current_user || current_user&.admin? %>
      <%= link_to 'delete comment', article_comment_path(article_id: comment.article.id, id: comment.id), method: :delete, data: { confirm: 'Are you sure?' } %>
      <%= link_to 'edit comment', edit_article_comment_path(article_id: comment.article.id, id: comment.id)%>
  <% end %>
  <hr />
</div>

app/views/comments/_form.html.erb
<%= render 'common/errors', model: @comment %>

<%= form_for [@article, @comment], url: article_comments_path(@article, @comment) do |f| %>
  <p>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>

<%= render 'form' %>

<%= link_to 'delete comment', article_comment_path(article_id: @comment.article.id, id: @comment.id), method: :delete, data: { confirm: 'Are you sure?' } %>

<%= link_to 'Back', article_path(@article) %>