config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'articles#index'
  get 'articles/index'

  # get 'articles', to: 'articles#index'
  # get 'articles/new', to: 'articles#new', as: 'new_article'
  # post 'articles', to: 'articles#create'
  # get 'articles/:id', to: 'articles#show', as: 'article'
  # get 'articles/:id/edit', to: 'articles#edit', as: 'edit_article'
  # patch 'articles/:id', to: 'articles#update'
  # delete 'articles/:id', to: 'articles#destroy' - resources generuje to wszystko

  resources :articles do
    get 'toggle_visibility', on: :member
    get 'most_commented', on: :member
    resources :comments do
      resources :scores, only: %i[create destroy]
    end
    resources :likes, only: %i[create destroy]
  end

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord

  mount_uploader :cover, CoverUploader

  validates :title, presence: true, length: {  minimum: 5 }

  has_many :comments, dependent: :destroy
  belongs_to :user
  has_many :likes
  has_many :users, through: :likes

  scope :published, -> { where(published: true) }

  scope :most_commented, -> { order(comments_count: :desc).first }

  def tags=(tag_list)
    tag_list = sanitize_tags(tag_list) if tag_list.is_a?(String)
    super(tag_list)
  end

  def css_class
    if published?
      'normal'
    else
      'unpublished'
    end
  end

  private

  def sanitize_tags(text)
    text.downcase.split.uniq
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :find_article, only: [:show, :edit, :update, :destroy, :toggle_visibility]
  before_action :authenticate_user!, except: [:show, :index]
  before_action :authorize_user, only: [:destroy, :edit, :update]

  def index
    if current_user&.admin?
      @articles = Article.all
    else
      @articles = Article.published
    end

    @most_commented = @articles.most_commented
    @articles = @articles.includes(:user).order(id: :desc).page(params[:page]).per(2)
    @articles = @articles.where("? =any(tags)", params[:q]) if params[:q].present?
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user if current_user
    if @article.save
      flash[:notice] = "You have successfuly added a new Article."
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def show
    @comment = Comment.new
    @score = Score.new
    @like = Like.find_or_initialize_by(article: @article, user: current_user)

    respond_to do |format|
      format.html do
        @article.increment!(:views_count)
        render
      end

      format.json do
        sleep(rand(100)/10)
        render json: {
          id: @article.id,
          title: @article.title,
          text: @article.text,
          views_count: @article.views_count,
          likes_count: @article.likes_count,
          comments_count: @article.comments_count
        }
      end
    end

  end

  def edit
  end

  def update
    if @article.update(article_params) || current_user&.admin?
      flash[:notice] = "You have successfuly updated this Article."
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    flash[:alert] = "You have deleted the Article."
    redirect_to articles_path
  end

  def toggle_visibility
    return redirect_to articles_path, error: 'Not found' unless current_user&.admin?
    @article.toggle!(:published)
    redirect_to articles_path, notice: "Your article visibility has been changed"
  end


  private

  def authorize_user
    if @article.user != current_user && !current_user&.admin?
      flash[:alert] = "You are not allowed to do this."
      redirect_to articles_path
      return false
    end
  true
  end

  def article_params
    article_params = params.require(:article).permit(:title, :text, :tags, :cover)
  end

  def find_article
    @article = if current_user&.admin?
                Article.find(params[:id])
              else
                Article.published.find(params[:id])
              end
  end

end

app/views/articles/_form.html.erb
<%= render 'common/errors', model: @article %>

<%= form_for @article.becomes(Article) do |f| %>
<div class="form-group">
  <%= f.label :title %>
  <%= f.text_field :title, class: 'form-control' %>
</div>
<div class="form-group">
  <%= f.label :text %><br>
  <%= f.text_area :text, class: 'form-control' %>
</div>
<div class="form-group">
  <%= f.label :tags %><br>
  <%= f.text_field :tags, class: 'form-control' %>
</div>
<div class="form-group">
  <label>Cover photo</label>
  <%= image_tag(@article.cover_url) if @article.cover? %>
  <%= f.file_field :cover %>
</div>
<div class="form-group">
  <%= f.submit class: 'btn btn-primary'%>
</div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render 'form' %>

<%= link_to 'Delete', article_path(@article), method: :delete, data: { confirm: 'Are you sure?'} %>

<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1><%= link_to'My Articles', articles_path %></h1>
<br>
<br>

    <%= link_to 'New Article', new_article_path %>
    <%= form_tag articles_path, method: :get do %>
      <div class="input-group">
        <%= text_field_tag :q, params[:q], class: "form-control" %>
          <span class="input-group-btn">
            <%= submit_tag "Search", class: "btn btn-default" %>
          </span>
      </div>
    <% end %>
<% if @articles.any? %>
<h4>Najczęściej komentowany Artykuł:</h4>
<%= link_to @most_commented.title, article_path(@most_commented) %><br />
Liczba komentarzy: <%= @most_commented.comments_count %>
<% end %>
<br>
<br>
<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Text</th>
      <th>Author:</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th>Comments:</th>
    </tr>
  </thead>
    <tbody>
      <% @articles.each do |article| %>
        <tr class="<%= article.css_class %>">
          <td><%= article.title %> </td>
          <td><%= article.text %></td>
          <td><%= article.user.email %></td>
          <td><%= link_to 'Show', article_path(article) %></td>
          <td>
          <% if article.user == current_user || current_user&.admin? %>
            <%= link_to 'Edit', edit_article_path(article) %>
          <% end %>
          </td>
          <td>
          <% if article.user == current_user || current_user&.admin? %>
            <%= link_to 'Delete', article_path(article), method: :delete, data: { confirm: 'Are you sure?'} %>
          <% end %>
          </td>
          <td><%= link_to 'Summary', article_path(article), class: 'btn btn-info summary', id: "summary-#{article.id}" %></td>
          <td><%= article.comments.count %></td
        </tr>
      <% end %>
  </tbody>
</table>
<br>
Articles: <%= @articles.count %>
<%= paginate @articles, theme: 'twitter-bootstrap-4' %>

app/views/articles/new.html.erb
<h1>New article</h1>


<%= render 'form' %>

<%= link_to 'Back to Articles', articles_path %>

app/views/articles/show.html.erb
<h1>My Article</h1>
<%= pluralize(@article.likes_count, 'person') %> liked this article
<% if @like.persisted? %>
<i class="fa fa-thumbs-down"><%= link_to 'Unlike', article_like_path(@article, @like), method: :delete %></i>
<% else %>
<i class="fa fa-thumbs-up"> <%= link_to 'Like', article_likes_path(@article), method: :post %> </i>
<% end %>
<p>
 <strong>Title:</strong>
  <%= @article.title %>
</p>
<p>
  <%= image_tag(@article.cover.url, alt:'Image') if @article.cover? %>
</p>

<p>
  <strong>Author:</strong>
   <%= @article.user.email %>
<p>
  <strong>Text:</strong>
  <%= simple_format(@article.text) %>
</p>
<p>
  <strong>Tags:</strong>
  <% @article.tags.map do |tag| %>
    <%= link_to tag, articles_path(q: tag), class:"badge badge-pill badge-dark" %>
  <% end %>
</p>
<p>
  <% if sponsored_article?(@article) %>
  <strong>Artykuł sponsorowany przed firmę <%= @article.company.name %></strong>
  <% end %>
</p>

<% if sponsored_article?(@article) %>
<p>Komentarze zablokowane</p>
<% else %>
    <h2>Comments</h2>

    <%= render @article.comments.includes(:user)%>

    <%if current_user %>
      <h3>Add comment:</h3>
      <%= render 'comments/form' %>
    <% end %>

<% end %>

<%= link_to 'Back to Articles', articles_path %> |

<% if @article.user == current_user || current_user&.admin? %>
  <%= link_to 'Edit Article', edit_article_path(@article) %> |
<% end %>
<% if @article.user == current_user || current_user&.admin? %>
  <%= link_to 'Delete Article', article_path(@article), method: :delete, data: { confirm: 'Are you sure?'} %> |
<% end %>

<% if current_user&.admin? %>
  <%= link_to @article.published? ? "Unpublish" : "Publish", toggle_visibility_article_path(@article) %>
<% end %>